---
- hosts: dev
  ignore_errors: yes
  tasks:
  - yum:
      name: httpd
      state: latest 
    notify: restart httpd 
  - yum:
      name: ftp
      state: latest
  handlers:
  - name: restart httpd 
    systemd:
      name: httpd
      state: restart 

