---
- hosts: prod
  tasks: 
  - apt:
      name: apache2
      state: latest
    when: '"Debian" in ansible_distribution'
  - yum:
      name: httpd
      state: latest
    when: '"RedHat" in ansible_distribution'

