---
- hosts: prod
  tasks: 
    - apt:
        name: apache2
        state: latest
      when: ansible_distribution == "Debian"

    - yum:
        name: httpd
        state: latest
      when: ansible_distribution == "RedHat"

