---
- name: Example Playbook with Variables
  hosts: webservers
  become: yes

  vars:
    package_name: httpd
    service_name: httpd
    document_root: /var/www/html
    index_file: index.html
    index_content: "Welcome to Seven Mentor for Devops. Current topic is  Ansible managed server!"

  tasks:
    - name: Install package
      yum:
        name: "{{ package_name }}"
        state: present

    - name: Start and enable service
      service:
        name: "{{ service_name }}"
        state: started
        enabled: yes

    - name: Create document root
      file:
        path: "{{ document_root }}"
        state: directory

    - name: Deploy index page
      copy:
        dest: "{{ document_root }}/{{ index_file }}"
        content: "{{ index_content }}"
