---
- name: Pull and deploy Docker container on node2
  hosts: node2
  become: yes
  gather_facts: no
  vars_files:
    -  vars.yml

  tasks:

    - name: Pull Docker image from Docker Hub
      community.docker.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        source: pull

    - name: Run Docker container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ image_name }}:{{ image_tag }}"
        state: started
        restart_policy: always
        ports:
          - "{{ app_port }}:80"
