---
- name: Configure and start HTTPD
  hosts: webservers
  become: yes

  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Enable and start httpd service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Copy index.html file
      copy:
        content: "Welcome to Apache Server!"
        dest: /var/www/html/index.html

- name: Configure and start VSFTPD
  hosts: mysql
  become: yes

  tasks:
    - name: Install vsftpd
      yum:
        name: vsftpd
        state: present

    - name: Enable and start vsftpd service
      service:
        name: vsftpd
        state: started
        enabled: yes

    - name: Allow anonymous login (example)
      lineinfile:
        path: /etc/vsftpd/vsftpd.conf
        regexp: '^anonymous_enable='
        line: 'anonymous_enable=YES'
      notify: Restart vsftpd

  handlers:
    - name: Restart vsftpd
      service:
        name: vsftpd
        state: restarted
  
