---
- name: Install and start  httpd
  hosts: webservers
  become: yes  # Run with sudo privileges

  tasks:
    - name: Install httpd package
      yum:
        name: httpd
        state: present
    
    - name: Create a sample index.html file                                          #Second task in first playbook
      copy:
        content: |
          <html>
            <head><title>Welcome to My Web Server</title></head>
            <body>
              <h1>Hello, World!</h1>
              <p>This is a sample index.html page served by Apache.</p>
            </body>
          </html>
        dest: /var/www/html/index.html
        owner: apache
        group: apache
        mode: '0644'

    - name: Start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes

