---
- name: Install Packages and Start Services (for Red Hat)
  hosts: all   # ✅ Or use 'redhat' group in your inventory
  become: true

  vars:
    packages_to_install:
      - git       # Add any packages you need
      - wget
      - curl
      - vim
      - httpd

    services_to_start:
      - httpd     # Add more services here if needed

    index_html_content: |
      <!DOCTYPE html>
      <html>
      <head>
          <title>Welcome to DevOps</title>
      </head>
      <body>
          <h1>🚀 Your Server is LIVE: {{ inventory_hostname }}</h1>
          <p>This page was deployed by Ghanshyam using Ansible.</p>
      </body>
      </html>

  tasks:
    - name: Install required packages
      yum:
        name: "{{ packages_to_install }}"
        state: present
      when: ansible_os_family == "RedHat"
      tags: install
      notify: restart services

    - name: Update all packages to the latest version
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"
      tags: update

    - name: Ensure services are started and enabled
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: "{{ services_to_start }}"
      when: ansible_os_family == "RedHat"
      tags: service

    - name: Create index.html and write content
      copy:
        content: "{{ index_html_content }}"
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
      when: ansible_os_family == "RedHat"
      notify: restart services
      tags: web

  handlers:
    - name: restart services
      service:
        name: "{{ item }}"
        state: restarted
      loop: "{{ services_to_start }}"

